# ===============================
# CONFIGURAÇÕES DO SERVIDOR
# ===============================
server.port=8080

# ===============================
# CONFIGURAÇÕES DO BANCO DE DADOS
# ===============================
spring.datasource.url=jdbc:h2:mem:eventosdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=


#http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===============================
# CONFIGURAÇÕES DO JPA / HIBERNATE
# ===============================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect